In [1]:
import os
os.chdir("sequencial")
print("Diretório atual:", os.getcwd())

Diretório atual: /home/jals/Documents/ualg/projeto_backup/analise/sequencial

In [5]:
ficheiros = [f for f in os.listdir() if f.startswith("tempos_") and "threads" not in f]
print(ficheiros)

['tempos_512.csv', 'tempos_1024.csv', 'tempos_256.csv', 'tempos_2048.csv']

In [7]:
ficheiro = "tempos_256.csv"

with open(ficheiro, "r") as f:
    for i, linha in enumerate(f):
        if i >= 15: break  # mostrar primeiras 15 linhas
        print(linha.strip())

Execução,Tempo_real, Tempo_user, Tempo_sys
Uptime antes da execução:  18:24:53 up  4:10, 13 users,  load average: 0.75, 1.81, 3.80
1,0.083,0.078,0.004
2,0.085,0.081,0.004
3,0.082,0.082,0
4,0.084,0.084,0.001
5,0.083,0.083,0
6,0.086,0.082,0.004
7,0.084,0.084,0
8,0.087,0.087,0
9,0.086,0.086,0
10,0.079,0.079,0
11,0.081,0.077,0.004
12,0.089,0.088,0
13,0.078,0.077,0.001

In [9]:
import pandas as pd

In [26]:
from io import StringIO

with open(ficheiro, "r") as f:
    linhas_validas = []
    for linha in f:
        if linha.strip().split(',')[0].isdigit():
            linhas_validas.append(linha)

df = pd.read_csv(StringIO("".join(linhas_validas)), names=[
    "Execucao", "Tempo_real", "Tempo_user", "Tempo_sys"
])

df.pr()

In [27]:
carregar_ficheiro_sequencial("tempos_256.csv")

✔️ Criado: df_sequencial_256

    Execucao  Tempo_real  Tempo_user  Tempo_sys
0          1       0.083       0.078      0.004
1          2       0.085       0.081      0.004
2          3       0.082       0.082      0.000
3          4       0.084       0.084      0.001
4          5       0.083       0.083      0.000
5          6       0.086       0.082      0.004
6          7       0.084       0.084      0.000
7          8       0.087       0.087      0.000
8          9       0.086       0.086      0.000
9         10       0.079       0.079      0.000
10        11       0.081       0.077      0.004
11        12       0.089       0.088      0.000
12        13       0.078       0.077      0.001
13        14       0.082       0.078      0.004
14        15       0.082       0.082      0.000
15        16       0.084       0.080      0.004
16        17       0.084       0.083      0.000
17        18       0.083       0.083      0.000
18        19       0.083       0.083      0.001
19        20       0.078       0.078      0.000
20        21       0.079       0.080      0.000
21        22       0.078       0.074      0.004
22        23       0.077       0.073      0.004
23        24       0.082       0.078      0.004
24        25       0.080       0.080      0.000
25        26       0.087       0.075      0.012
26        27       0.080       0.080      0.000
27        28       0.082       0.074      0.008
28        29       0.082       0.077      0.004
29        30       0.084       0.079      0.004

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Execucao    30 non-null     int64
 1   Tempo_real  30 non-null     float64
 2   Tempo_user  30 non-null     float64
 3   Tempo_sys   30 non-null     float64
dtypes: float64(3), int64(1)
memory usage: 1.1 KB

In [14]:
df.describe()

        Execucao  Tempo_real  Tempo_user  Tempo_sys
count  30.000000   30.000000   30.000000  30.000000
mean   15.500000    0.082467    0.080167   0.002233
std     8.803408    0.002980    0.003806   0.002861
min     1.000000    0.077000    0.073000   0.000000
25%     8.250000    0.080250    0.078000   0.000000
50%    15.500000    0.082500    0.080000   0.001000
75%    22.750000    0.084000    0.083000   0.004000
max    30.000000    0.089000    0.088000   0.012000

In [17]:
os.chdir("..")
os.chdir("openmp")
print(os.getcwd())

/home/jals/Documents/ualg/projeto_backup/analise/openmp

In [18]:
ficheiros = [f for f in os.listdir() if f.startswith("tempos_") and "threads" in f and f.endswith(".csv")]
print(ficheiros)

['tempos_256_threads6.csv', 'tempos_256_threads2.csv', 'tempos_1024_threads8.csv', 'tempos_512_threads8.csv', 'tempos_512_threads2.csv', 'tempos_2048_threads10.csv', 'tempos_1024_threads6.csv', 'tempos_256_threads4.csv', 'tempos_1024_threads10.csv', 'tempos_1024_threads4.csv', 'tempos_2048_threads6.csv', 'tempos_256_threads10.csv', 'tempos_512_threads6.csv', 'tempos_512_threads10.csv', 'tempos_1024_threads2.csv', 'tempos_512_threads4.csv', 'tempos_2048_threads2.csv', 'tempos_2048_threads4.csv', 'tempos_2048_threads8.csv', 'tempos_256_threads8.csv']

In [19]:
ficheiro = "tempos_512_threads2.csv"

with open(ficheiro, "r") as f:
    for i, linha in enumerate(f):
        if i >= 15: break
        print(linha.strip())

Execução,Tempo_real,Tempo_user,Tempo_sys,Tempo_extra
Uptime antes da execução:  16:47:18 up  2:33, 26 users,  load average: 2.07, 0.66, 1.01
1,0.558,0.617,0.008,0.494156
2,0.473,0.615,0.004,0.409670
3,0.554,0.617,0.004,0.452426
4,0.509,0.613,0.02,0.422036
5,0.463,0.648,0.004,0.397001
6,0.444,0.614,0.004,0.378198
7,0.415,0.603,0.004,0.356251
8,0.456,0.609,0.008,0.397179
9,0.448,0.618,0.008,0.384498
10,0.514,0.615,0.004,0.441611
11,0.511,0.598,0.012,0.450194
12,0.451,0.612,0.004,0.390789
13,0.465,0.613,0.008,0.404144

In [22]:
ficheiro = "tempos_256_threads2.csv"

with open(ficheiro, "r") as f:
    linhas_validas = [linha for linha in f if linha.strip().split(',')[0].isdigit()]

df_openmp = pd.read_csv(StringIO("".join(linhas_validas)), names=[
    "Execucao", "Tempo_real", "Tempo_user", "Tempo_sys", "Tempo_extra"
])

df_openmp

    Execucao  Tempo_real  Tempo_user  Tempo_sys  Tempo_extra
0          1       0.088       0.088      0.000     0.072266
1          2       0.088       0.088      0.000     0.070577
2          3       0.094       0.089      0.000     0.077984
3          4       0.083       0.089      0.000     0.066864
4          5       0.092       0.089      0.000     0.075099
5          6       0.095       0.087      0.004     0.077548
6          7       0.090       0.085      0.004     0.072799
7          8       0.089       0.089      0.000     0.071456
8          9       0.083       0.089      0.000     0.067255
9         10       0.089       0.085      0.004     0.072196
10        11       0.062       0.084      0.004     0.046679
11        12       0.088       0.088      0.000     0.073046
12        13       0.082       0.099      0.000     0.063441
13        14       0.089       0.088      0.000     0.067841
14        15       0.087       0.083      0.004     0.071926
15        16       0.076       0.089      0.000     0.059626
16        17       0.082       0.092      0.000     0.065609
17        18       0.086       0.082      0.004     0.070324
18        19       0.088       0.084      0.004     0.073280
19        20       0.088       0.088      0.000     0.072494
20        21       0.081       0.090      0.004     0.062800
21        22       0.076       0.088      0.000     0.060842
22        23       0.088       0.084      0.004     0.071368
23        24       0.088       0.088      0.000     0.071160
24        25       0.087       0.086      0.000     0.071529
25        26       0.070       0.085      0.004     0.054072
26        27       0.087       0.087      0.000     0.070765
27        28       0.088       0.084      0.004     0.072112
28        29       0.075       0.088      0.000     0.059664
29        30       0.083       0.080      0.008     0.067459

In [21]:
df.describe()

        Execucao  Tempo_real  Tempo_user  Tempo_sys
count  30.000000   30.000000   30.000000  30.000000
mean   15.500000    0.082467    0.080167   0.002233
std     8.803408    0.002980    0.003806   0.002861
min     1.000000    0.077000    0.073000   0.000000
25%     8.250000    0.080250    0.078000   0.000000
50%    15.500000    0.082500    0.080000   0.001000
75%    22.750000    0.084000    0.083000   0.004000
max    30.000000    0.089000    0.088000   0.012000

In [23]:
media_openmp = df_openmp["Tempo_real"].mean()
desvio_openmp = df_openmp["Tempo_real"].std()

print(f"Média OpenMP: {media_openmp:.6f} s")
print(f"Desvio padrão OpenMP: {desvio_openmp:.6f} s")

Média OpenMP: 0.084733 s
Desvio padrão OpenMP: 0.007066 s

In [24]:
media_sequencial = df['Tempo_real'].mean()

# Calculo do speedup e eficiencia da matriz 256 no openmp

In [25]:
threads = 2
speedup = media_sequencial / media_openmp
eficiencia = (speedup / threads) * 100

print(f"Speedup: {speedup:.3f}")
print(f"Eficiência: {eficiencia:.2f}%")

Speedup: 0.973
Eficiência: 48.66%